# Generated by Django 4.2.7 on 2025-06-12 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Descrição')),
                ('color', models.CharField(default='#007bff', help_text='Código hexadecimal da cor (ex: #007bff)', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone (ex: book, microphone)', max_length=50, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(help_text='Nome da pessoa responsável pela reunião', max_length=40, verbose_name='Responsável')),
                ('title', models.CharField(help_text='Título principal da reunião', max_length=60, verbose_name='Tema/Título')),
                ('description', models.TextField(help_text='Descrição detalhada do que será abordado', max_length=300, verbose_name='Descrição')),
                ('meeting_date', models.DateField(verbose_name='Data da Reunião')),
                ('meeting_time', models.TimeField(verbose_name='Horário da Reunião')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duração estimada em minutos', verbose_name='Duração (minutos)')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso Horário')),
                ('meeting_format', models.CharField(choices=[('youtube', 'YouTube Live'), ('zoom', 'Zoom Meeting'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('jitsi', 'Jitsi Meet'), ('discord', 'Discord'), ('other', 'Outro')], max_length=20, verbose_name='Formato da Reunião')),
                ('meeting_url', models.URLField(help_text='URL para acessar a reunião online', validators=[django.core.validators.URLValidator()], verbose_name='Link da Reunião')),
                ('backup_url', models.URLField(blank=True, help_text='URL alternativa caso a principal falhe', verbose_name='Link Backup')),
                ('meeting_password', models.CharField(blank=True, help_text='Senha para acesso (se necessária)', max_length=50, verbose_name='Senha da Reunião')),
                ('access_type', models.CharField(choices=[('public', 'Público - Qualquer um pode solicitar participação'), ('private', 'Privado - Apenas por convite'), ('restricted', 'Restrito - Aprovação manual obrigatória')], default='public', max_length=20, verbose_name='Tipo de Acesso')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Deixe vazio para ilimitado', null=True, verbose_name='Máximo de Participantes')),
                ('requires_approval', models.BooleanField(default=True, help_text='Participantes precisam de aprovação para entrar', verbose_name='Requer Aprovação')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Permitir Comentários')),
                ('allow_ratings', models.BooleanField(default=True, verbose_name='Permitir Avaliações')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Reunião Recorrente')),
                ('agenda', models.TextField(blank=True, help_text='Pauta detalhada da reunião', verbose_name='Agenda')),
                ('prerequisites', models.TextField(blank=True, help_text='O que os participantes devem saber/ter', verbose_name='Pré-requisitos')),
                ('materials', models.TextField(blank=True, help_text='Links para materiais de apoio', verbose_name='Materiais')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=200, verbose_name='Tags')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_approval', 'Aguardando Aprovação'), ('approved', 'Aprovada'), ('published', 'Publicada'), ('in_progress', 'Em Andamento'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada'), ('postponed', 'Adiada')], default='draft', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('join_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas de Participação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meetings.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-meeting_date', '-meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('attended', 'Compareceu'), ('no_show', 'Não Compareceu')], default='pending', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, help_text='Mensagem enviada na solicitação', max_length=500, verbose_name='Mensagem')),
                ('response_message', models.TextField(blank=True, help_text='Resposta sobre a aprovação/rejeição', verbose_name='Resposta')),
                ('attended', models.BooleanField(default=False, verbose_name='Compareceu')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Entrou em')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Saiu em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_participations', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Participação em Reunião',
                'verbose_name_plural': 'Participações em Reuniões',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='MeetingCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado'), ('revoked', 'Revogado')], default='pending', max_length=20, verbose_name='Status')),
                ('permissions', models.JSONField(default=list, help_text='Lista de permissões do cooperador', verbose_name='Permissões')),
                ('message', models.TextField(blank=True, help_text='Mensagem enviada na solicitação', verbose_name='Mensagem')),
                ('response_message', models.TextField(blank=True, help_text='Resposta do criador da reunião', verbose_name='Resposta')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cooperations', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('cooperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cooperador')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Cooperação em Reunião',
                'verbose_name_plural': 'Cooperações em Reuniões',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'cooperator')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='cooperators',
            field=models.ManyToManyField(blank=True, related_name='cooperated_meetings', through='meetings.MeetingCooperation', to=settings.AUTH_USER_MODEL, verbose_name='Cooperadores'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_meetings', through='meetings.MeetingParticipation', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fixado')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetings.meeting', verbose_name='Reunião')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='meetings.comment', verbose_name='Comentário Pai')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], verbose_name='Avaliação')),
                ('review', models.TextField(blank=True, max_length=500, verbose_name='Comentário')),
                ('aspects', models.JSONField(default=dict, help_text='Avaliações por aspecto (conteúdo, organização, etc.)', verbose_name='Aspectos')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Avaliação Anônima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meetings.meeting', verbose_name='Reunião')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meeting', '-rating'], name='meetings_ra_meeting_3a5aeb_idx')],
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meeting_approval', 'Reunião Aprovada'), ('meeting_rejection', 'Reunião Rejeitada'), ('participation_approved', 'Participação Aprovada'), ('participation_rejected', 'Participação Rejeitada'), ('cooperation_request', 'Solicitação de Cooperação'), ('cooperation_approved', 'Cooperação Aprovada'), ('meeting_reminder', 'Lembrete de Reunião'), ('new_comment', 'Novo Comentário'), ('meeting_cancelled', 'Reunião Cancelada')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='meetings_no_user_id_f3c5e8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_date', 'meeting_time'], name='meetings_me_meeting_11da87_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'published_at'], name='meetings_me_status_6020c7_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['category', 'status'], name='meetings_me_categor_1008fc_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['creator', 'status'], name='meetings_me_creator_066c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['meeting', '-created_at'], name='meetings_co_meeting_41edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='meetings_co_author__fa42a7_idx'),
        ),
    ]
