# Generated by Django 4.2.7 on 2025-06-12 03:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meeting_approval', 'Reunião Aprovada'), ('meeting_rejection', 'Reunião Rejeitada'), ('participation_approved', 'Participação Aprovada'), ('participation_rejected', 'Participação Rejeitada'), ('cooperation_request', 'Solicitação de Cooperação'), ('cooperation_approved', 'Cooperação Aprovada'), ('meeting_reminder', 'Lembrete de Reunião'), ('new_comment', 'Novo Comentário'), ('meeting_cancelled', 'Reunião Cancelada')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='meetingcooperation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cooperação em Reunião', 'verbose_name_plural': 'Cooperações em Reuniões'},
        ),
        migrations.AlterModelOptions(
            name='meetingparticipation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Participação em Reunião', 'verbose_name_plural': 'Participações em Reuniões'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Nome do ícone (ex: book, microphone)', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Fixado'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Curtidas'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='meetings.comment', verbose_name='Comentário Pai'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='access_type',
            field=models.CharField(choices=[('public', 'Público - Qualquer um pode solicitar participação'), ('private', 'Privado - Apenas por convite'), ('restricted', 'Restrito - Aprovação manual obrigatória')], default='public', max_length=20, verbose_name='Tipo de Acesso'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True, help_text='Pauta detalhada da reunião', verbose_name='Agenda'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Permitir Comentários'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='allow_ratings',
            field=models.BooleanField(default=True, verbose_name='Permitir Avaliações'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='backup_url',
            field=models.URLField(blank=True, help_text='URL alternativa caso a principal falhe', verbose_name='Link Backup'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cooperators',
            field=models.ManyToManyField(blank=True, related_name='cooperated_meetings', through='meetings.MeetingCooperation', to=settings.AUTH_USER_MODEL, verbose_name='Cooperadores'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duração estimada em minutos', verbose_name='Duração (minutos)'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Reunião Recorrente'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='join_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de Participação'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='materials',
            field=models.TextField(blank=True, help_text='Links para materiais de apoio', verbose_name='Materiais'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe vazio para ilimitado', null=True, verbose_name='Máximo de Participantes'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_format',
            field=models.CharField(choices=[('youtube', 'YouTube Live'), ('zoom', 'Zoom Meeting'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('jitsi', 'Jitsi Meet'), ('discord', 'Discord'), ('other', 'Outro')], default='meet', max_length=20, verbose_name='Formato da Reunião'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_password',
            field=models.CharField(blank=True, help_text='Senha para acesso (se necessária)', max_length=50, verbose_name='Senha da Reunião'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_meetings', through='meetings.MeetingParticipation', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='O que os participantes devem saber/ter', verbose_name='Pré-requisitos'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado em'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Participantes precisam de aprovação para entrar', verbose_name='Requer Aprovação'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=200, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso Horário'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AddField(
            model_name='meetingcooperation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cooperations', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='meetingcooperation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='meetingcooperation',
            name='message',
            field=models.TextField(blank=True, help_text='Mensagem enviada na solicitação', verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='meetingcooperation',
            name='permissions',
            field=models.JSONField(default=list, help_text='Lista de permissões do cooperador', verbose_name='Permissões'),
        ),
        migrations.AddField(
            model_name='meetingcooperation',
            name='response_message',
            field=models.TextField(blank=True, help_text='Resposta do criador da reunião', verbose_name='Resposta'),
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_participations', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Compareceu'),
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrou em'),
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saiu em'),
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='message',
            field=models.TextField(blank=True, help_text='Mensagem enviada na solicitação', max_length=500, verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='response_message',
            field=models.TextField(blank=True, help_text='Resposta sobre a aprovação/rejeição', verbose_name='Resposta'),
        ),
        migrations.AddField(
            model_name='rating',
            name='aspects',
            field=models.JSONField(default=dict, help_text='Avaliações por aspecto (conteúdo, organização, etc.)', verbose_name='Aspectos'),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Avaliação Anônima'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetings.meeting', verbose_name='Reunião'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(help_text='Descrição detalhada do que será abordado', max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(help_text='URL para acessar a reunião online', validators=[django.core.validators.URLValidator()], verbose_name='Link da Reunião'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='responsible',
            field=models.CharField(help_text='Nome da pessoa responsável pela reunião', max_length=40, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending_approval', 'Aguardando Aprovação'), ('approved', 'Aprovada'), ('published', 'Publicada'), ('in_progress', 'Em Andamento'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada'), ('postponed', 'Adiada')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(help_text='Título principal da reunião', max_length=60, verbose_name='Tema/Título'),
        ),
        migrations.AlterField(
            model_name='meetingcooperation',
            name='cooperator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cooperador'),
        ),
        migrations.AlterField(
            model_name='meetingcooperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='meetingcooperation',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião'),
        ),
        migrations.AlterField(
            model_name='meetingcooperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado'), ('revoked', 'Revogado')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meetingcooperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em'),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião'),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('attended', 'Compareceu'), ('no_show', 'Não Compareceu')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meetingparticipation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meetings.meeting', verbose_name='Reunião'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, max_length=500, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['meeting', '-created_at'], name='meetings_co_meeting_41edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='meetings_co_author__fa42a7_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_date', 'meeting_time'], name='meetings_me_meeting_11da87_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'published_at'], name='meetings_me_status_6020c7_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['category', 'status'], name='meetings_me_categor_1008fc_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['creator', 'status'], name='meetings_me_creator_066c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['meeting', '-rating'], name='meetings_ra_meeting_3a5aeb_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Reunião'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='meetings_no_user_id_f3c5e8_idx'),
        ),
    ]
